#!/usr/bin/env python3
"""
Convert CSV (domain_name,a_record_ip,parse_cnt) to config/example.toml format.

Usage:
  python3 scripts/csv_to_toml.py -i pdns_20260523_top10w.csv -o config/generated.toml --top 1000 --ttl 300

By default the script emits A records using column `domain_name` and `a_record_ip`.
If `--top N` is given and `parse_cnt` is present, rows are sorted by parse_cnt descending.
"""

from __future__ import annotations
import argparse
import csv
import sys
from typing import List, Dict, Optional


def toml_quoted(s: str) -> str:
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'


def write_toml(records: List[Dict], out_path: str) -> None:
    header = (
        "# Generated by scripts/csv_to_toml.py\n"
        "# Each [[records]] block contains qname, qtype, ttl and answers\n\n"
    )
    with open(out_path, 'w', encoding='utf-8') as f:
        f.write(header)
        for r in records:
            f.write('[[records]]\n')
            f.write(f'qname   = {toml_quoted(r["qname"])}\n')
            f.write(f'qtype   = {toml_quoted(r["qtype"])}\n')
            f.write(f'ttl     = {int(r["ttl"])}\n')
            answers = r.get('answers', [])
            ans_list = ', '.join(toml_quoted(a) for a in answers)
            f.write(f'answers = [{ans_list}]\n\n')


def read_csv(in_path: str, col_map: Dict[str, str]) -> List[Dict]:
    out = []
    with open(in_path, newline='', encoding='utf-8') as csvfile:
        reader = csv.DictReader(csvfile)
        for row in reader:
            # skip empty rows
            if not any((v or '').strip() for v in row.values()):
                continue
            q = (row.get(col_map['domain']) or '').strip()
            ip = (row.get(col_map['ip']) or '').strip()
            cnt = (row.get(col_map.get('count', ''), '') or '').strip()
            record = {
                'qname': q,
                'qtype': col_map.get('default_qtype', 'A'),
                'ttl': col_map.get('default_ttl', 300),
                'answers': [ip] if ip else [],
                'parse_cnt': int(cnt) if cnt and cnt.isdigit() else 0,
            }
            out.append(record)
    return out


def main(argv: Optional[List[str]] = None) -> int:
    p = argparse.ArgumentParser(description='CSV -> dnshijack TOML config')
    p.add_argument('-i', '--input', required=True, help='Input CSV file')
    p.add_argument('-o', '--output', required=True, help='Output TOML file')
    p.add_argument('--domain-col', default='domain_name', help='CSV column for domain name')
    p.add_argument('--ip-col', default='a_record_ip', help='CSV column for A record')
    p.add_argument('--count-col', default='parse_cnt', help='CSV column for popularity count (optional)')
    p.add_argument('--ttl', type=int, default=300, help='TTL to use for generated records')
    p.add_argument('--qtype', default='A', help='qtype to emit (default A)')
    p.add_argument('--top', type=int, default=0, help='If >0, keep only top N by count')
    p.add_argument('--min-count', type=int, default=0, help='Minimum parse_cnt to include')
    args = p.parse_args(argv)

    col_map = {
        'domain': args.domain_col,
        'ip': args.ip_col,
        'count': args.count_col,
        'default_ttl': args.ttl,
        'default_qtype': args.qtype,
    }

    try:
        rows = read_csv(args.input, col_map)
    except FileNotFoundError:
        print(f'Input file not found: {args.input}', file=sys.stderr)
        return 2

    # filter by min-count
    if args.min_count:
        rows = [r for r in rows if r.get('parse_cnt', 0) >= args.min_count]

    # sort by parse_cnt desc if requested
    rows.sort(key=lambda r: r.get('parse_cnt', 0), reverse=True)

    if args.top > 0:
        rows = rows[:args.top]

    # normalize TTL and qtype
    for r in rows:
        r['ttl'] = int(args.ttl)
        r['qtype'] = args.qtype
        # drop entries with no answer or empty qname
        if not r['answers'] or not r['qname']:
            r['skip'] = True
        else:
            r['skip'] = False

    rows = [r for r in rows if not r['skip']]

    write_toml(rows, args.output)
    print(f'Wrote {len(rows)} records to {args.output}')
    return 0

if __name__ == '__main__':
    raise SystemExit(main())
